name: Build Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: dongle
            config_dir: dongle_config/config
            board: nice_nano_v2
            shield: dual_dongle
            artifact_name: dual_dongle
          - name: crosses_left
            config_dir: crosses_42_firmware/config
            board: nice_nano_v2
            shield: crosses_left
            artifact_name: crosses_left
          - name: crosses_right
            config_dir: crosses_42_firmware/config
            board: nice_nano_v2
            shield: crosses_right
            artifact_name: crosses_right
          - name: corne_left
            config_dir: corne_firmware/config
            board: nice_nano_v2
            shield: corne_left
            artifact_name: corne_left
          - name: corne_right
            config_dir: corne_firmware/config
            board: nice_nano_v2
            shield: corne_right
            artifact_name: corne_right

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache west modules
        uses: actions/cache@v3
        env:
          cache-name: cache-west-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('{0}/west.yml', matrix.config_dir)) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l ${{ matrix.config_dir }}

      - name: West Update
        run: west update

      - name: West Zephyr Export
        run: west zephyr-export

      - name: Build Firmware
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/${{ matrix.config_dir }}"

      - name: Rename Artifact
        run: cp build/zephyr/zmk.uf2 ${{ matrix.artifact_name }}-nice_nano_v2-zmk.uf2

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}-nice_nano_v2-zmk.uf2
