name: Build Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: dongle
            app_dir: dongle_config
            config_path: config
            board: nice_nano_v2
            shield: dual_dongle
            artifact_name: dual_dongle
          - name: crosses_left
            app_dir: crosses_42_firmware
            config_path: config
            board: nice_nano_v2
            shield: crosses_left
            artifact_name: crosses_left
          - name: crosses_right
            app_dir: crosses_42_firmware
            config_path: config
            board: nice_nano_v2
            shield: crosses_right
            artifact_name: crosses_right
          - name: corne_left
            app_dir: corne_firmware
            config_path: config
            board: nice_nano_v2
            shield: corne_left
            artifact_name: corne_left
          - name: corne_right
            app_dir: corne_firmware
            config_path: config
            board: nice_nano_v2
            shield: corne_right
            artifact_name: corne_right

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trust workspace in git
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git config --global --add safe.directory ${GITHUB_WORKSPACE}/${{ matrix.app_dir }}/${{ matrix.config_path }}
          git config --global --add safe.directory ${GITHUB_WORKSPACE}/${{ matrix.app_dir }}

      - name: Debug Info
        run: |
          id
          git --version
          west --version
          ls -la

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-west-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('{0}/{1}/west.yml', matrix.app_dir, matrix.config_path)) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        working-directory: ${{ matrix.app_dir }}
        run: west init -l ${{ matrix.config_path }}

      - name: Validate Manifest
        working-directory: ${{ matrix.app_dir }}
        run: west manifest --validate

      - name: West Update
        working-directory: ${{ matrix.app_dir }}
        run: west update

      - name: West Zephyr Export
        working-directory: ${{ matrix.app_dir }}
        run: west zephyr-export

      - name: Build Firmware
        working-directory: ${{ matrix.app_dir }}
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/${{ matrix.app_dir }}/${{ matrix.config_path }}"

      - name: Rename Artifact
        working-directory: ${{ matrix.app_dir }}
        run: cp build/zephyr/zmk.uf2 ../${{ matrix.artifact_name }}-nice_nano_v2-zmk.uf2

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}-nice_nano_v2-zmk.uf2
